### ISSUE TITLE
[BUG] about page - scrollbars in content

### ISSUE THREAD

**Issue by maitrish1** [OperationCode/front-end#1775] opened 2023-11-22 07:21 UTC
# Bug Report
## What is the current behavior?
In the about page, under each picture there are scrollbars for each writing.

## What is the expected behavior?
There shouldn't be any scrollbars and the entire writing should be visible.

## What steps did you take to get this behavior?
Went to /about page

### Operating System
Ubuntu 22.04.3 LTS

### Browser
[Version 1.60.110 Chromium: 119.0.6045.105 (Official Build) (64-bit)](https://brave.com/latest/)
### Is This A Third-Party Issue?
No

### Screenshots
![Screenshot from 2023-11-22 11-50-18](https://github.com/OperationCode/front-end/assets/64683146/9d353181-53cd-4d4c-b091-f332d179a5cb)

**Comment by kylemh** [comment] 2023-11-22 07:58
Hmm must be a regression from https://github.com/OperationCode/front-end/pull/1762

Here's what it looked like before: https://operation-code-lhm3i4o4k-operation-code.vercel.app/about

<img width="1482" alt="Screenshot 2023-11-22 at 2 56 43 PM" src="https://github.com/OperationCode/front-end/assets/9523719/4bdb6f8e-0dd5-4fc8-8e8b-ec394dc36f6e">
<img width="500" alt="Screenshot 2023-11-22 at 2 56 51 PM" src="https://github.com/OperationCode/front-end/assets/9523719/32ab33e2-85b3-4de0-8d6a-23f8e8094b6d">

@subhajit20 interested in resolving the bug?

**Comment by maitrish1** [comment] 2023-11-22 07:59
@kylemh I would love to solve this. I am already on it.

**Comment by kylemh** [comment] 2023-11-22 08:00
Understood @maitrish1 

We gave up long ago on assigning issues because people would volunteer, get assigned, and go silent for months effectively parking the issue. So, whoever resolves it first!

**Comment by maitrish1** [comment] 2023-11-22 08:03
@kylemh on it , Thanks :)

**Comment by kylemh** [comment] 2023-12-17 14:03
resolved!

**Closed** 2023-12-17 14:03 UTC
Labels: beginner friendly, Type: Bug, good first issue
